name: Update cache image

#on:
#  schedule:
#     Run every Sunday at midnight
#    - cron: '0 0 * * 0'
#
#  repository_dispatch:
#    types: build-docker-cache

on: push

jobs:
  update-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Free disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          df -h

      # ssh checkout needed for https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#push-using-ssh-deploy-keys
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ssh-key: '${{ secrets.SSH_PRIVATE_KEY }}'

      #- name: Update Cache File
      #  id: updateCacheFile
      #  uses: smartcontractkit/docker-cache@99a8aec1b4eb98e0627aefe07223c9d8bec5ba33
      #  with:
      #    actionType: 'UPDATE_CACHE_FILE'

      - name: Get current date
        id: getDate
        run: echo "::set-output name=date::$(date -u +"%Y-%m-%dT%H%MZ")"

      #- name: Publish to Registry
      #  uses: elgohr/Publish-Docker-Github-Action@2.14
      #  with:
      #    name: 'smartcontract/builder-cache'
      #    dockerfile: 'builder-cache.Dockerfile'
      #    tags: '${{ steps.updateCacheFile.outputs.builderVersion }}-${{ steps.getDate.outputs.date }}'
      #    username: ${{ secrets.DOCKER_USERNAME }}
      #    password: ${{ secrets.DOCKER_PASSWORD }}

      # TODO REMOVE ME
      #- name: Login to ECR
      #  id: ecr
      #  uses: elgohr/ecr-login-action@1.0.0
      #  with:
      #    access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #    secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #    region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to ECR
        id: get-ecr-login
        uses:  Konsentus/action.assume-ecr-login@master
        env:
          AWS_REGION: eu-west-2
          AWS_ACCOUNT_ROLE: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          AWS_ACCOUNT_ID: "795953128386"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: "Login to AWS ECR"
        run: ${{ steps.get-ecr-login.outputs.login }}

      - name: Publish the build-cache image to ECR
        uses: elgohr/Publish-Docker-Github-Action@2.17
        with:
          name: ${{ secrets.AWS_ECR_ACCOUNT_URL }}
          username: ${{ steps.ecr.outputs.username }}
          password: ${{ steps.ecr.outputs.password }}
          registry: ${{ steps.ecr.outputs.registry }}
          dockerfile: builder-cache.Dockerfile
          #tags: '${{ steps.updateCacheFile.outputs.builderVersion }}-${{ steps.getDate.outputs.date }}'
          tags: ${{ steps.getDate.outputs.date }}

      #- name: Update docker files
      #  uses: smartcontractkit/docker-cache@99a8aec1b4eb98e0627aefe07223c9d8bec5ba33
      #  with:
      #    actionType: 'UPDATE_DOCKER_FILES'

      #- name: Open PR with updated cache and docker files
      #  uses: peter-evans/create-pull-request@v2.7.0
      #  with:
      #    title: 'Update docker cache image'
      #    commit-message: 'Update docker cache image'
